[package]
name = "largequeryfile-demo"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "create_mock_csv"
path = "src/bin/create_mock_csv.rs"

[[bin]]
name = "convert_csv2parquet"
path = "src/bin/convert_csv2parquet.rs"

[[bin]]
name = "performance_query"
path = "src/bin/performance_query.rs"

[dependencies]
pretty_env_logger = "0.5"
log = "0.4"
duckdb = {version = "1.4",features = ["bundled"]}
csv = "1.3"
rand = "0.9"
fake = { version = "4.4", features = ["derive"] }
parquet = "57.0"
arrow = "57.0"
rayon = "1.10"
chrono = "0.4"
polars = { version = "0.44", features = ["lazy", "parquet", "csv", "strings"] }

